Repository TeamMyDaily/4most-Android, pull requests merged in 2021-01, with the labels that each got.

#4 [MOD] #1 - change main toolbar text
  app/src/main/java/org/mydaily/ui/view/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: 4z7l, Review Required

#7 Feature/3 daily fragment
  app/build.gradle
  app/src/main/java/org/mydaily/data/model/Keyword.kt
  app/src/main/java/org/mydaily/ui/adapter/DailyKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/view/MainActivity.kt
  app/src/main/java/org/mydaily/ui/view/daily/DailyFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/DailyViewModel.kt
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_arrow_forward.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_daily.xml
  app/src/main/res/layout/item_daily_goal.xml
  app/src/main/res/layout/layout_daily_goal_first.xml
  app/src/main/res/layout/layout_daily_goal_second.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, Review Required

#10 Feature/9 sign in activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/di/ViewModelModule.kt
  app/src/main/java/org/mydaily/ui/view/signin/SignInActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/SignInViewModel.kt
  app/src/main/java/org/mydaily/util/LoginPatternCheckUtil.kt
  app/src/main/java/org/mydaily/util/extension/ViewExt.kt
  app/src/main/res/drawable/ic_checkbox_off.xml
  app/src/main/res/drawable/ic_checkbox_on.xml
  app/src/main/res/drawable/rectangle_fill_gray_radius_15.xml
  app/src/main/res/drawable/rectangle_fill_orange_radius_15.xml
  app/src/main/res/drawable/rectangle_gray_radius_15.xml
  app/src/main/res/drawable/rectangle_orange_radius_15.xml
  app/src/main/res/drawable/selector_btn_sign_in.xml
  app/src/main/res/drawable/selector_checkbox.xml
  app/src/main/res/drawable/selector_et_sign_in.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 4z7l, Review Required

#16 Feature/13 daily fragment
  app/src/main/java/org/mydaily/data/model/Keyword.kt
  app/src/main/java/org/mydaily/ui/adapter/DailyKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/view/daily/DailyFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/DailyViewModel.kt
  app/src/main/java/org/mydaily/util/CalendarUtil.kt
  app/src/main/res/drawable/ic_01.xml
  app/src/main/res/drawable/ic_02.xml
  app/src/main/res/drawable/ic_03.xml
  app/src/main/res/drawable/ic_04.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_calendar_off.xml
  app/src/main/res/drawable/ic_calendar_on.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/rectangle_white_radius_40.xml
  app/src/main/res/drawable/selector_arrow_down_up.xml
  app/src/main/res/drawable/selector_btn_calendar.xml
  app/src/main/res/layout/fragment_daily.xml
  app/src/main/res/layout/item_daily_goal.xml
  app/src/main/res/layout/layout_daily_goal_first.xml
  app/src/main/res/layout/layout_daily_goal_parent.xml
  app/src/main/res/layout/layout_daily_goal_second.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, Review Required

#19 Feature/14 toolbar setting
  app/src/main/java/org/mydaily/ui/view/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, Review Required

#20 Feature/13 daily fragment
  app/src/main/java/org/mydaily/ui/view/daily/DailyFragment.kt
  app/src/main/res/drawable/ic_today.xml
  app/src/main/res/layout/fragment_daily.xml
Labels: 4z7l, Review Required

#25 Feature/23 goal fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/data/model/Goal.kt
  app/src/main/java/org/mydaily/di/ViewModelModule.kt
  app/src/main/java/org/mydaily/ui/adapter/GoalReportAdapter.kt
  app/src/main/java/org/mydaily/ui/view/MainActivity.kt
  app/src/main/java/org/mydaily/ui/view/goal/GoalFragment.kt
  app/src/main/java/org/mydaily/ui/view/goal/detail/GoalDetailActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/GoalViewModel.kt
  app/src/main/java/org/mydaily/util/BindingAdapter.kt
  app/src/main/java/org/mydaily/util/extension/ViewExt.kt
  app/src/main/res/color/selector_bottom_navi.xml
  app/src/main/res/drawable/ic_btn_plus.xml
  app/src/main/res/drawable/ic_daily.xml
  app/src/main/res/drawable/ic_goal.xml
  app/src/main/res/drawable/ic_light_arrow_left.xml
  app/src/main/res/drawable/ic_light_arrow_right.xml
  app/src/main/res/drawable/ic_my.xml
  app/src/main/res/drawable/ic_report.xml
  app/src/main/res/drawable/rectangle_fill_gray_radius_30.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_goal.xml
  app/src/main/res/layout/item_keyword_goal.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, Review Required

#27 Feature/26 my page
  app/src/main/java/org/mydaily/ui/adapter/MyPageKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/view/MainActivity.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/MyPageViewModel.kt
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/rectangle_fill_orange_radius_0_0_15_15.xml
  app/src/main/res/drawable/rectangle_white_radius_20.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_page_keyword_list.xml
  app/src/main/res/menu/menu_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, P0, Review Required

#28 Feature/5 keyword list activity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/di/ViewModelModule.kt
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordListActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/KeywordViewModel.kt
  app/src/main/res/color/selector_chip.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/layout/activity_keyword_list.xml
  app/src/main/res/menu/menu_keyword_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 4z7l, Review Required, sgh002400

#30 Feature/29 goal UI
  app/src/main/java/org/mydaily/data/model/Goal.kt
  app/src/main/java/org/mydaily/ui/adapter/GoalReportAdapter.kt
  app/src/main/java/org/mydaily/ui/view/goal/GoalFragment.kt
  app/src/main/java/org/mydaily/ui/view/goal/detail/GoalDetailActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/GoalViewModel.kt
  app/src/main/java/org/mydaily/util/BindingAdapter.kt
  app/src/main/java/org/mydaily/util/CalendarUtil.kt
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/fragment_goal.xml
  app/src/main/res/layout/item_keyword_goal.xml
  app/src/main/res/layout/layout_goal_fragment_keyword_exist.xml
  app/src/main/res/layout/layout_goal_fragment_not_keyword.xml
  app/src/main/res/layout/layout_goal_fragment_not_keyword_this_week.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, Review Required

#34 Feature/6 report and remind
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/data/model/ReportListData.kt
  app/src/main/java/org/mydaily/di/ViewModelModule.kt
  app/src/main/java/org/mydaily/ui/adapter/RemindvpAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/ReportDetailAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/ReportKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/view/remind/OnItemClick.kt
  app/src/main/java/org/mydaily/ui/view/remind/RemindDetailWriteActivity.kt
  app/src/main/java/org/mydaily/ui/view/remind/RemindFragment.kt
  app/src/main/java/org/mydaily/ui/view/remind/RemindWriteFragment.kt
  app/src/main/java/org/mydaily/ui/view/remind/ReportDetailFragment.kt
  app/src/main/java/org/mydaily/ui/view/remind/ReportFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/ReportViewModel.kt
  app/src/main/res/drawable/achievement_container.xml
  app/src/main/res/drawable/achviement_container_orange.xml
  app/src/main/res/drawable/btn_write_complete.xml
  app/src/main/res/drawable/btn_write_incomplete.xml
  app/src/main/res/drawable/day_record_container.xml
  app/src/main/res/drawable/day_record_divider.xml
  app/src/main/res/drawable/ic_arrow_report_back.xml
  app/src/main/res/drawable/ic_arrow_report_detail.xml
  app/src/main/res/drawable/ic_arrow_report_detail_white.xml
  app/src/main/res/drawable/ic_arrow_report_forward.xml
  app/src/main/res/drawable/ic_this_week.xml
  app/src/main/res/drawable/keyword_container.xml
  app/src/main/res/drawable/remind_tb_background.xml
  app/src/main/res/drawable/remind_write_textbox.xml
  app/src/main/res/drawable/report_detail_goal_container.xml
  app/src/main/res/drawable/report_detail_goal_container_orange.xml
  app/src/main/res/drawable/sb_rate_custom.xml
  app/src/main/res/layout/activity_remind_detail_write.xml
  app/src/main/res/layout/fragment_remind.xml
  app/src/main/res/layout/fragment_remind_write.xml
  app/src/main/res/layout/fragment_report.xml
  app/src/main/res/layout/fragment_report_detail.xml
  app/src/main/res/layout/keyword_list_item.xml
  app/src/main/res/layout/report_list_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: In Progress, Review Required, mdb1217

#40 Feature/39 goal UI
  app/src/main/java/org/mydaily/data/model/Goal.kt
  app/src/main/java/org/mydaily/data/model/domain/Goal.kt
  app/src/main/java/org/mydaily/ui/adapter/GoalReportAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/MyPageKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/view/goal/GoalFragment.kt
  app/src/main/java/org/mydaily/ui/view/goal/detail/GoalDetailActivity.kt
  app/src/main/java/org/mydaily/ui/view/remind/RemindWriteFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/GoalViewModel.kt
  app/src/main/java/org/mydaily/util/BindingAdapter.kt
  app/src/main/res/color/selector_checked.xml
  app/src/main/res/drawable/ic_goal_off.xml
  app/src/main/res/drawable/ic_goal_on.xml
  app/src/main/res/drawable/selector_goal.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/fragment_goal.xml
  app/src/main/res/layout/item_keyword_goal.xml
  app/src/main/res/layout/layout_goal_fragment_keyword_exist.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, Review Required

#44 Feature/39 goal UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/di/ViewModelModule.kt
  app/src/main/java/org/mydaily/ui/view/goal/GoalFragment.kt
  app/src/main/java/org/mydaily/ui/view/goal/detail/GoalAddActivity.kt
  app/src/main/java/org/mydaily/ui/view/goal/detail/GoalDetailActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/GoalViewModel.kt
  app/src/main/java/org/mydaily/util/BindingAdapter.kt
  app/src/main/res/color/selector_checked.xml
  app/src/main/res/drawable/selector_goal.xml
  app/src/main/res/layout/activity_goal_add.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/item_keyword_goal.xml
  app/src/main/res/menu/menu_goal_add.xml
  app/src/main/res/menu/menu_goal_detail.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, P0, Review Required

#47 [FEAT] #43 - SignIn Feature
  app/src/main/java/org/mydaily/ui/view/signin/SignInActivity.kt
  app/src/main/java/org/mydaily/ui/view/signup/SignUpTermsActivity.kt
  app/src/main/java/org/mydaily/util/LoginPatternCheckUtil.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/strings.xml
Labels: In Progress, Review Required, mdb1217

#49 Feature/45 keyword settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/data/model/domain/KeywordPriority.kt
  app/src/main/java/org/mydaily/ui/adapter/ItemTouchHelperCallback.kt
  app/src/main/java/org/mydaily/ui/adapter/ItemTouchHelperListener.kt
  app/src/main/java/org/mydaily/ui/adapter/KeywordDefineAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/KeywordPriorityAdapter.kt
  app/src/main/java/org/mydaily/ui/view/keyword/settings/KeywordDefineAddFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/settings/KeywordDefineFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/settings/KeywordPriorityFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/settings/KeywordSettingsActivity.kt
  app/src/main/java/org/mydaily/util/extension/ViewExt.kt
  app/src/main/res/drawable/divider_recyclerview.xml
  app/src/main/res/drawable/ic_list.xml
  app/src/main/res/layout/activity_keyword_settings.xml
  app/src/main/res/layout/fragment_keyword_define.xml
  app/src/main/res/layout/fragment_keyword_define_add.xml
  app/src/main/res/layout/fragment_keyword_priority.xml
  app/src/main/res/layout/item_keyword_define.xml
  app/src/main/res/layout/item_keyword_priority.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, P2, Review Required

#50 Feature/24 keyword popup activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/ui/adapter/KeywordPopupViewPagerAdapter.kt
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordPopupFirstFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordPopupSecondFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordPopupThirdFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/detail/KeywordListActivity.kt
  app/src/main/java/org/mydaily/ui/view/keyword/detail/KeywordPopupActivity.kt
  app/src/main/res/drawable/selector_tab_indicator.xml
  app/src/main/res/layout/activity_keyword_popup.xml
  app/src/main/res/layout/fragment_keyword_popup_first.xml
  app/src/main/res/layout/fragment_keyword_popup_second.xml
  app/src/main/res/layout/fragment_keyword_popup_third.xml
  app/src/main/res/values/strings.xml
Labels: Review Required, sgh002400

#60 Feature/59 sign network
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/data/local/FourMostPreference.kt
  app/src/main/java/org/mydaily/data/remote/api/UserService.kt
  app/src/main/java/org/mydaily/di/ViewModelModule.kt
  app/src/main/java/org/mydaily/ui/view/user/SignInActivity.kt
  app/src/main/java/org/mydaily/ui/view/user/SignUpActivity.kt
  app/src/main/java/org/mydaily/ui/view/user/SignUpTermsActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/SignInViewModel.kt
  app/src/main/java/org/mydaily/ui/viewmodel/SignUpViewModel.kt
  app/src/main/java/org/mydaily/ui/viewmodel/UserViewModel.kt
  app/src/main/java/org/mydaily/util/Event.kt
  app/src/main/java/org/mydaily/util/extension/ViewExt.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up_terms.xml
Labels: 4z7l, P0, Review Required

#63 Feature/58 goal network
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/data/model/domain/Goal.kt
  app/src/main/java/org/mydaily/data/model/network/response/ResGoalGet.kt
  app/src/main/java/org/mydaily/data/remote/api/GoalService.kt
  app/src/main/java/org/mydaily/data/remote/datasource/GoalRemoteDataSource.kt
  app/src/main/java/org/mydaily/data/remote/datasource/GoalRemoteDataSourceImpl.kt
  app/src/main/java/org/mydaily/data/repository/GoalRepo.kt
  app/src/main/java/org/mydaily/data/repository/GoalRepoImpl.kt
  app/src/main/java/org/mydaily/ui/adapter/GoalReportAdapter.kt
  app/src/main/java/org/mydaily/ui/view/goal/GoalFragment.kt
  app/src/main/java/org/mydaily/ui/view/goal/detail/GoalAddActivity.kt
  app/src/main/java/org/mydaily/ui/view/goal/detail/GoalDetailActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/GoalViewModel.kt
  app/src/main/java/org/mydaily/util/BindingAdapter.kt
  app/src/main/java/org/mydaily/util/CalendarUtil.kt
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/fragment_goal.xml
  app/src/main/res/layout/item_keyword_goal.xml
Labels: 4z7l, Review Required

#65 선택한 키워드 리스트 전달 로직
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordAddActivity.kt
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordSelectActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/KeywordViewModel.kt
Labels: P0, Review Required, sgh002400

#70 Feature/64 my page UI
  app/src/main/java/org/mydaily/data/model/network/request/ReqKeywordPriority.kt
  app/src/main/java/org/mydaily/data/model/network/response/ResKeywordListGet.kt
  app/src/main/java/org/mydaily/data/model/network/response/ResTaskKeywordGet.kt
  app/src/main/java/org/mydaily/data/remote/api/KeywordService.kt
  app/src/main/java/org/mydaily/data/remote/api/UserService.kt
  app/src/main/java/org/mydaily/data/remote/datasource/KeywordRemoteDataSource.kt
  app/src/main/java/org/mydaily/data/remote/datasource/KeywordRemoteDataSourceImpl.kt
  app/src/main/java/org/mydaily/data/remote/datasource/UserRemoteDataSource.kt
  app/src/main/java/org/mydaily/data/remote/datasource/UserRemoteDataSourceImpl.kt
  app/src/main/java/org/mydaily/data/repository/KeywordRepo.kt
  app/src/main/java/org/mydaily/data/repository/KeywordRepoImpl.kt
  app/src/main/java/org/mydaily/data/repository/UserRepo.kt
  app/src/main/java/org/mydaily/data/repository/UserRepoImpl.kt
  app/src/main/java/org/mydaily/ui/adapter/MyPageCurrentKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/MyPageKeywordListAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/MyPageKeywordPriorityAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/ViewPagerAdapter.kt
  app/src/main/java/org/mydaily/ui/view/custom/MyPageBottomSheetDialog.kt
  app/src/main/java/org/mydaily/ui/view/mypage/KeywordListFragment.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageCurrentKeywordFragment.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageFragment.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageKeywordListFragment.kt
  app/src/main/java/org/mydaily/ui/view/mypage/RecordKeywordFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/KeywordViewModel.kt
  app/src/main/res/drawable/ic_trash.xml
  app/src/main/res/drawable/ic_x.xml
  app/src/main/res/drawable/selector_pin.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_current_keyword.xml
  app/src/main/res/layout/fragment_my_page_keyword_list.xml
  app/src/main/res/layout/fragment_record_keyword.xml
  app/src/main/res/layout/item_my_page_current_keyword.xml
  app/src/main/res/layout/item_my_page_keyword_list.xml
  app/src/main/res/layout/item_my_page_keyword_priority.xml
  app/src/main/res/layout/item_my_page_record_keyword.xml
  app/src/main/res/layout/layout_modal_bottom_sheet_my_page.xml
  app/src/main/res/layout/layout_my_page_current_keyword_list.xml
  app/src/main/res/layout/layout_my_page_current_keyword_priority.xml
  app/src/main/res/values/strings.xml
Labels: 4z7l, Review Required

#73 Feature/72 keyword settings
  app/src/main/java/org/mydaily/data/local/FourMostPreference.kt
  app/src/main/java/org/mydaily/data/model/network/request/ReqKeywordDefine.kt
  app/src/main/java/org/mydaily/data/model/network/response/ResKeywordDefinitionGet.kt
  app/src/main/java/org/mydaily/data/remote/api/KeywordService.kt
  app/src/main/java/org/mydaily/data/remote/datasource/KeywordRemoteDataSource.kt
  app/src/main/java/org/mydaily/data/remote/datasource/KeywordRemoteDataSourceImpl.kt
  app/src/main/java/org/mydaily/data/repository/KeywordRepo.kt
  app/src/main/java/org/mydaily/data/repository/KeywordRepoImpl.kt
  app/src/main/java/org/mydaily/ui/adapter/ItemTouchHelperListener.kt
  app/src/main/java/org/mydaily/ui/adapter/KeywordDefineAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/KeywordPriorityAdapter.kt
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordSelectActivity.kt
  app/src/main/java/org/mydaily/ui/view/keyword/settings/KeywordDefineAddFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/settings/KeywordDefineFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/settings/KeywordPriorityFragment.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageCurrentKeywordFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/KeywordViewModel.kt
  app/src/main/res/layout/fragment_keyword_define_add.xml
  app/src/main/res/layout/item_keyword_priority.xml
Labels: 4z7l, P1, Review Required

#87 Feature/77 splash view
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/splash.json
  app/src/main/java/org/mydaily/ui/adapter/ServiceExplainViewPagerAdapter.kt
  app/src/main/java/org/mydaily/ui/view/splash/SplashActivity.kt
  app/src/main/java/org/mydaily/ui/view/splash/service/ServiceExplainActivity.kt
  app/src/main/java/org/mydaily/ui/view/splash/service/ServiceExplainFirstFragment.kt
  app/src/main/java/org/mydaily/ui/view/splash/service/ServiceExplainSecondFragment.kt
  app/src/main/java/org/mydaily/ui/view/splash/service/ServiceExplainThirdFragment.kt
  app/src/main/res/drawable/image_explain_01.9.png
  app/src/main/res/drawable/image_explain_02.9.png
  app/src/main/res/drawable/image_explain_03.9.png
  app/src/main/res/layout/activity_service_explain.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_service_explain_first.xml
  app/src/main/res/layout/fragment_service_explain_second.xml
  app/src/main/res/layout/fragment_service_explain_third.xml
  app/src/main/res/raw/apple.json
  app/src/main/res/raw/splashview.json
  app/src/main/res/values/strings.xml
Labels: P0, sgh002400

#89 Feature/55 report and remind network
  app/src/main/java/org/mydaily/data/model/network/response/ResReportDetailGet.kt
  app/src/main/java/org/mydaily/di/ViewModelModule.kt
  app/src/main/java/org/mydaily/ui/adapter/RemindViewPagerAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/ReportDetailAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/ReportKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/view/remind/OnItemClick.kt
  app/src/main/java/org/mydaily/ui/view/remind/RemindDetailWriteActivity.kt
  app/src/main/java/org/mydaily/ui/view/remind/RemindFragment.kt
  app/src/main/java/org/mydaily/ui/view/remind/RemindWriteFragment.kt
  app/src/main/java/org/mydaily/ui/view/remind/ReportDetailFragment.kt
  app/src/main/java/org/mydaily/ui/view/remind/ReportFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/ReportViewModel.kt
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_thin_arrow_back.xml
  app/src/main/res/layout/fragment_report.xml
  app/src/main/res/layout/layout_empty_report.xml
  app/src/main/res/layout/report_list_item.xml
Labels: Review Required, mdb1217
