Repository TeamMyDaily/4most-Android, pull requests merged in 2021-03, with the labels that each got.

#99 Feature/98 refactor keyword guide
  app/src/main/java/org/mydaily/ui/view/keyword/add/KeywordAddActivity.kt
  app/src/main/java/org/mydaily/ui/view/keyword/guide/KeywordGuideSelectDeepFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/guide/KeywordGuideSelectFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/method/KeywordMethodFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/KeywordViewModel.kt
  app/src/main/java/org/mydaily/util/extension/ViewExt.kt
  app/src/main/res/layout/fragment_keyword_guide_select.xml
  app/src/main/res/layout/fragment_keyword_guide_select_deep.xml
  app/src/main/res/layout/fragment_keyword_method.xml
  app/src/main/res/values/themes.xml
Labels: 4z7l, Review Required

#101 Feature/100 refactor keyword add
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mydaily/ui/adapter/KeywordAddAdapter.kt
  app/src/main/java/org/mydaily/ui/view/keyword/add/KeywordAddActivity.kt
  app/src/main/java/org/mydaily/ui/view/keyword/add/KeywordAddDetailFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/add/KeywordAddFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/method/KeywordMethodFragment.kt
  app/src/main/java/org/mydaily/ui/viewmodel/KeywordViewModel.kt
  app/src/main/java/org/mydaily/util/KoreanInWordCheckUtil.kt
  app/src/main/res/drawable-xhdpi/rectangle_cherry_radius_8.xml
  app/src/main/res/drawable-xhdpi/rectangle_fill_white_gray_radius_8.xml
  app/src/main/res/drawable/ic_cross.xml
  app/src/main/res/layout/fragment_keyword_add.xml
  app/src/main/res/layout/fragment_keyword_add_detail.xml
  app/src/main/res/layout/item_important_four_value.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Review Required, complete, mdb1217, refactor

#104 Feature/103 refactor keyword architecture
  app/src/main/java/org/mydaily/ui/adapter/KeywordPopupViewPagerAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/ViewPagerStateAdapter.kt
  app/src/main/java/org/mydaily/ui/view/custom/NonSwipeViewPager.kt
  app/src/main/java/org/mydaily/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/org/mydaily/ui/view/keyword/add/KeywordAddDetailFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/add/KeywordAddFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/guide/KeywordGuideSelectDeepFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/guide/KeywordGuideSelectFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/method/KeywordMethodFragment.kt
  app/src/main/java/org/mydaily/ui/view/keyword/popup/KeywordPopupActivity.kt
  app/src/main/java/org/mydaily/ui/view/splash/service/ServiceExplainActivity.kt
  app/src/main/java/org/mydaily/ui/viewmodel/KeywordViewModel.kt
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/fragment_keyword_add.xml
  app/src/main/res/layout/fragment_keyword_add_detail.xml
  app/src/main/res/layout/fragment_keyword_guide_select.xml
  app/src/main/res/layout/fragment_keyword_guide_select_deep.xml
  app/src/main/res/layout/fragment_keyword_method.xml
Labels: 4z7l, Review Required

#105 Feature/102 refactor my page
  app/src/main/java/org/mydaily/ui/adapter/MyPageCurrentKeywordAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/MyPageKeywordListAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/MyPageKeywordPriorityAdapter.kt
  app/src/main/java/org/mydaily/ui/adapter/ViewPagerAdapter.kt
  app/src/main/java/org/mydaily/ui/view/custom/MyPageBottomSheetDialog.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageCurrentKeywordFragment.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageFragment.kt
  app/src/main/java/org/mydaily/ui/view/mypage/MyPageKeywordListFragment.kt
  app/src/main/res/drawable/ic_compass.xml
  app/src/main/res/drawable/ic_list_line_2.xml
  app/src/main/res/drawable/ic_modify_black.xml
  app/src/main/res/drawable/ic_modify_gray.xml
  app/src/main/res/drawable/ic_pin_black.xml
  app/src/main/res/drawable/rectangle_white_card_radius_15.xml
  app/src/main/res/drawable/selector_btn_modify.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_current_keyword.xml
  app/src/main/res/layout/fragment_my_page_keyword_list.xml
  app/src/main/res/layout/item_my_page_current_keyword.xml
  app/src/main/res/layout/item_my_page_keyword_list.xml
  app/src/main/res/layout/item_my_page_keyword_priority.xml
  app/src/main/res/layout/layout_modal_bottom_sheet_my_page.xml
  app/src/main/res/layout/layout_my_page_current_keyword_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Review Required, mdb1217
